### ISSUE TITLE
Dott - new E-Scooter in Germany

### ISSUE THREAD

**Issue by altantosun** [ubahnverleih/WoBike#161] opened 2020-05-10 21:14 UTC
Any updates regarding dott? Would love to add that into my dashboard.

Official page: https://ridedott.com/

**Comment by yoshimo** [comment] 2020-05-11 09:44
Duplicate of https://github.com/ubahnverleih/WoBike/issues/81 .

**Closed** 2022-07-15 21:46 UTC
