### ISSUE TITLE
O-bike bike list API returns 

### ISSUE THREAD

**Issue by pnteresa** [ubahnverleih/WoBike#14] opened 2018-01-17 03:43 UTC
GET `https://mobile.o.bike/api/v1/bike/list?latitude=<LATITUDE>&longitude=<LONGITUDE>` returns error message for me:

```
{
    "data": {
        "code": 500,
        "error": "Server is busy,please try later"
    },
    "success": false,
    "errorCode": 400
}
```

Any idea? Thanks.

**Comment by PierrickP** [comment] 2018-01-17 09:58
Closed, duplicate of #8

**Closed by PierrickP** 2018-01-17 09:58 UTC

**Comment by ubahnverleih** [comment] 2018-01-17 10:32
short answer: They changed there API and we try to reverse engineering the new API. But its not so easy. You can look up the details at #8 and maybe help
